// Port of the time-slot resolution logic from scripts/lab_allocation.py
// (format_custom_time_label / infer_session_shift / resolve_slot_schedule).
// Kept behaviourally identical so schedules generated by this TS engine match
// the original Python pipeline exactly.

export type SlotInfo = {
  label: string;
  day: string;
  shift: string;
  num: number;
  time?: string;
  date?: string;
};

export const DEFAULT_SLOT_INFO: SlotInfo[] = [
  { label: "Thu 9 AM", day: "Thursday", shift: "Morning", num: 1 },
  { label: "Thu 12 PM", day: "Thursday", shift: "Afternoon", num: 2 },
  { label: "Thu 3 PM", day: "Thursday", shift: "Afternoon", num: 3 },
  { label: "Thu 6 PM", day: "Thursday", shift: "Evening", num: 4 },
  { label: "Fri 9 AM", day: "Friday", shift: "Morning", num: 5 },
  { label: "Fri 3 PM", day: "Friday", shift: "Afternoon", num: 6 },
  { label: "Fri 6 PM", day: "Friday", shift: "Evening", num: 7 },
];

export function formatCustomTimeLabel(rawTime: unknown): string {
  const raw = String(rawTime ?? "").trim();
  if (!raw) return "Slot";
  if (raw.toUpperCase().includes("AM") || raw.toUpperCase().includes("PM")) return raw;

  // Handle day-of-week prefixes like "Thu 10:00" or "Friday 14:00"
  const dayPrefixMatch = raw.match(/^([A-Za-z]+)\s+(.+)$/);
  if (dayPrefixMatch) {
    const dayPrefix = dayPrefixMatch[1];
    const timeRest = dayPrefixMatch[2].trim();
    const formatted = formatCustomTimeLabel(timeRest);
    return `${dayPrefix} ${formatted}`;
  }

  const m = /^(\d{1,2}):(\d{2})$/.exec(raw);
  if (m) {
    const hh = parseInt(m[1], 10);
    const mm = parseInt(m[2], 10);
    const period = hh >= 12 ? "PM" : "AM";
    const displayH = hh % 12 || 12;
    return `${displayH}:${String(mm).padStart(2, "0")} ${period}`;
  }
  return raw;
}

export function inferSessionShift(rawTime: unknown): { day: string; shift: string } {
  const rawLower = String(rawTime ?? "").toLowerCase();
  let day = "Thursday";
  if (rawLower.includes("mon")) day = "Monday";
  else if (rawLower.includes("tue")) day = "Tuesday";
  else if (rawLower.includes("wed")) day = "Wednesday";
  else if (rawLower.includes("thu")) day = "Thursday";
  else if (rawLower.includes("fri")) day = "Friday";
  else if (rawLower.includes("sat")) day = "Saturday";
  else if (rawLower.includes("sun")) day = "Sunday";

  const m = /(\d{1,2})(?::(\d{2}))?/.exec(rawLower);
  if (m) {
    let hh = parseInt(m[1], 10);
    if (rawLower.includes("pm") && hh < 12) hh += 12;
    else if (rawLower.includes("am") && hh === 12) hh = 0;
    let shift: string;
    if (hh < 12) shift = "Morning";
    else if (hh < 16) shift = "Afternoon";
    else if (hh < 19) shift = "Evening";
    else shift = "Night";
    return { day, shift };
  }
  return { day, shift: "Session" };
}

import { formatTimeSlot, normalizeTimeSlot } from "../time-slots";
import type { MegaGroupDefinition } from "../allocation-client";

export function extractIsoDate(value: unknown): string | null {
  const match = String(value ?? "").match(/\d{4}-\d{2}-\d{2}/);
  return match?.[0] ?? null;
}

export function deriveMegaGroupActiveDates(
  batchDates: unknown[] | null | undefined,
  megaGroup: MegaGroupDefinition,
  blockedDays: string[] = [],
): string[] {
  const normalizedBatchDates = Array.from(
    new Set((batchDates ?? []).map(extractIsoDate).filter((date): date is string => Boolean(date))),
  ).sort();
  let candidates = normalizedBatchDates;
  if (megaGroup.start_date) candidates = candidates.filter((date) => date >= megaGroup.start_date!);
  if (megaGroup.end_date) candidates = candidates.filter((date) => date <= megaGroup.end_date!);

  return candidates.filter((date) => {
    const parsed = new Date(`${date}T00:00:00`);
    const weekday = Number.isNaN(parsed.getTime())
      ? date
      : parsed.toLocaleDateString("en-US", { weekday: "long" });
    return !isBlockedDay(date, date, date, blockedDays) && !isBlockedDay(weekday, date, date, blockedDays);
  });
}

export interface MegaGroupDateRangeValidation {
  valid: boolean;
  activeDates: string[];
  maxActiveDates: number;
  overflowDates?: string[];
  message?: string;
}

export function validateMegaGroupDateRange(
  batchDates: unknown[] | null | undefined,
  megaGroup: MegaGroupDefinition,
  blockedDays: string[],
  daysPerGroup: number,
): MegaGroupDateRangeValidation {
  const maxActiveDates = Math.max(1, Math.trunc(Number(daysPerGroup)));
  const activeDates = deriveMegaGroupActiveDates(batchDates, megaGroup, blockedDays);
  const normalizedBatchDates = Array.from(
    new Set((batchDates ?? []).map(extractIsoDate).filter((date): date is string => Boolean(date))),
  );
  const hasActiveDates = normalizedBatchDates.length === 0 || activeDates.length > 0;
  const overflowDates = activeDates.length > maxActiveDates ? activeDates.slice(maxActiveDates) : [];

  return {
    valid: hasActiveDates,
    activeDates,
    maxActiveDates,
    overflowDates,
    ...(hasActiveDates
      ? {}
      : {
          message: `No active scheduling days found in the selected date range for Mega Group "${megaGroup.name}".`,
        }),
  };
}

export function getLatestValidMegaGroupEndDate(
  batchDates: unknown[] | null | undefined,
  startDate: string,
  blockedDays: string[],
  daysPerGroup: number,
): string | null {
  const dates = Array.from(
    new Set((batchDates ?? []).map(extractIsoDate).filter((date): date is string => Boolean(date))),
  ).sort();
  const eligible = dates.filter(
    (date) => date >= startDate && deriveMegaGroupActiveDates(dates, { name: "Date limit", start_date: startDate, end_date: date }, blockedDays).length <= daysPerGroup,
  );
  return eligible[eligible.length - 1] ?? null;
}

export function assertMegaGroupDateRanges(
  batchDates: unknown[] | null | undefined,
  megaGroups: MegaGroupDefinition[] | null | undefined,
  blockedDays: string[],
  daysPerGroup: number,
): void {
  for (const megaGroup of megaGroups ?? []) {
    const result = validateMegaGroupDateRange(batchDates, megaGroup, blockedDays, daysPerGroup);
    if (!result.valid) throw new Error(`${megaGroup.name}: ${result.message}`);
  }
}

export function isBlockedDay(day: string, label: string, raw: string, blockedDays?: string[]): boolean {
  if (!blockedDays || blockedDays.length === 0) return false;
  const cleanBlocked = blockedDays.map((b) => String(b).trim().toLowerCase());
  
  const rawLower = String(raw).toLowerCase();
  const dayLower = String(day).toLowerCase();
  const labelLower = String(label).toLowerCase();

  for (const b of cleanBlocked) {
    if (!b) continue;
    if (dayLower === b || labelLower.includes(b) || rawLower.includes(b)) return true;
    
    // Check if ISO date matches (e.g. 2026-09-18)
    const dateMatch = rawLower.match(/(\d{4}-\d{2}-\d{2})/) || labelLower.match(/(\d{4}-\d{2}-\d{2})/);
    if (dateMatch) {
      if (dateMatch[1] === b) return true;
      const d = new Date(`${dateMatch[1]}T00:00:00`);
      if (!isNaN(d.getTime())) {
        const weekday = d.toLocaleDateString("en-US", { weekday: "long" }).toLowerCase();
        const shortWeekday = d.toLocaleDateString("en-US", { weekday: "short" }).toLowerCase();
        const dayNum = String(d.getDate());
        if (b === weekday || b === shortWeekday || b === `day_${dayNum}` || b.includes(`${dayNum}th`) || b.includes(`${dayNum}st`) || b.includes(`${dayNum}nd`) || b.includes(`${dayNum}rd`)) {
          return true;
        }
      }
    }
  }
  return false;
}

export function resolveSlotSchedule(customSlots?: unknown[] | null, blockedDays?: string[]): SlotInfo[] {
  const initialSlots = !customSlots || customSlots.length === 0 ? [...DEFAULT_SLOT_INFO] : null;

  const slots: SlotInfo[] = [];
  let slotNum = 1;

  if (initialSlots) {
    for (const item of initialSlots) {
      if (!isBlockedDay(item.day, item.label, item.label, blockedDays)) {
        slots.push({ ...item, num: slotNum++ });
      }
    }
    return slots;
  }

  for (const item of customSlots!) {
    if (item && typeof item === "object" && !Array.isArray(item)) {
      const obj = item as Record<string, unknown>;
      const date = extractIsoDate(obj.date ?? obj.day ?? obj.label);
      const rawTime = obj.time ?? obj.label;
      const label = String(obj.label ?? (date && rawTime ? formatTimeSlot(`${date}@${String(rawTime)}`) : rawTime) ?? `Slot ${slotNum}`);
      const day = String(date ?? obj.day ?? "Thursday");
      const shift = String(obj.session ?? obj.shift ?? "Morning");
      const num = obj.num !== undefined ? Number(obj.num) : slotNum;
      if (!isBlockedDay(day, label, JSON.stringify(obj), blockedDays)) {
        slots.push({ label, day, shift, num, time: normalizeTimeSlot(rawTime) ?? undefined, date: date ?? undefined });
        slotNum += 1;
      }
    } else if (typeof item === "string" || typeof item === "number") {
      const rawStr = String(item).trim();
      if (!rawStr) continue;

      const dateMatch = rawStr.match(/^(\d{4}-\d{2}-\d{2})[@\s](.+)$/);
      if (dateMatch) {
        const dateStr = dateMatch[1];
        const timePart = dateMatch[2];
        const d = new Date(`${dateStr}T00:00:00`);
        const day = !isNaN(d.getTime()) ? d.toLocaleDateString("en-US", { weekday: "long" }) : "Thursday";
        const { shift } = inferSessionShift(timePart);
        const label = formatTimeSlot(rawStr);
        if (!isBlockedDay(dateStr, label, rawStr, blockedDays) && !isBlockedDay(day, label, rawStr, blockedDays)) {
          slots.push({ label, day: dateStr, shift, num: slotNum, time: normalizeTimeSlot(timePart) ?? undefined, date: dateStr });
          slotNum += 1;
        }
      } else {
        const label = formatCustomTimeLabel(rawStr);
        const { day, shift } = inferSessionShift(rawStr);
        if (!isBlockedDay(day, label, rawStr, blockedDays)) {
          slots.push({ label, day, shift, num: slotNum, time: normalizeTimeSlot(rawStr) ?? undefined });
          slotNum += 1;
        }
      }
    }
  }

  const originalOrder = new Map(slots.map((slot, index) => [slot, index]));
  return [...slots]
    .sort((a, b) => {
      const aDate = a.date ?? extractIsoDate(a.day);
      const bDate = b.date ?? extractIsoDate(b.day);
      const aTime = normalizeTimeSlot(a.time ?? a.label);
      const bTime = normalizeTimeSlot(b.time ?? b.label);
      if (aDate && bDate && aTime && bTime) {
        const aTimestamp = Date.parse(`${aDate}T${aTime}:00`);
        const bTimestamp = Date.parse(`${bDate}T${bTime}:00`);
        if (aTimestamp !== bTimestamp) return aTimestamp - bTimestamp;
      } else if (aDate !== bDate) {
        return aDate ? -1 : 1;
      }
      return (originalOrder.get(a) ?? 0) - (originalOrder.get(b) ?? 0);
    })
    .map((slot, index) => ({ ...slot, num: index + 1 }));
}
